# -*- coding: utf-8 -*-
"""SQL_inside_Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fwn0E8zEj3LuCnxDsKaXSbnMaIGBqaP7
"""

import sqlite3
import pandas as pd
import matplotlib.pyplot as plt
from google.colab import drive

# Connect to / create the SQLite Database
conn = sqlite3.connect("sales_data.db")

# Mount Google Drive
drive.mount('/content/drive')

# Load Sales.csv into pandas using exact folder path
df = pd.read_csv('/content/drive/MyDrive/Colab_Notebooks/DataXLab_datasource/Superstore_Sales_Financial.csv')
df.head()

#  Save into SQLite database table 'sales'
df.to_sql("sales", conn, if_exists="replace", index=False)

# Define the SQL Query (aggregating total quantity and calculated revenue by product Category)
query ="""
SELECT Category AS product_category, SUM(Quantity) AS total_qty, SUM(Quantity * Sales) AS revenue
FROM sales
GROUP BY Category;
"""

# Execute SQL query and load results into a Pandas DataFrame
summary_df=pd.read_sql_query(query, conn)
print("--- Sales Summary by Product Category---")
print(summary_df)

from matplotlib.typing import LineStyleType
import matplotlib.ticker as ticker

# Plot a basic Bar Chart for Revenue per Product Category using matplotlib

fig, ax = plt.subplots(figsize=(7, 4))
ax.bar(summary_df['product_category'], summary_df['revenue'], color = 'salmon', edgecolor= 'skyblue' )

# Format y-axis ticks to show $M (e.g., 4500000 -> $4.5M)
formatter = ticker.FuncFormatter(lambda x, pos: f'${x*1e-6:.1f}M')
ax.yaxis.set_major_formatter(formatter)

plt.title("Total Revenue by Product Category", fontsize=14, fontweight='bold')
plt.xlabel("Product Category", fontsize=12)
plt.ylabel("Revenue" ,fontsize=12)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.savefig("sales_chart.png", dpi=300)
plt.show()